# Generated by Django 4.2 on 2024-07-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='profilepic.jpg', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(default='profilepic.jpg', upload_to='profile_pictures'),
        ),
    ]
